title: olib Documentation
description: A lightweight C library for object serialization and format conversion
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
